### PR TITLE
Fixed loop

### LINKED ISSUE #86: Render issues in calendar overview
image

### PR DESCRIPTION
**Pull request by Fank**
Fixes #86 
We don't need to call setupPost because we only need to close the reponses list.

### CODE REVIEW

**Comment by Fank** [comment]
It would be nice if you could add me as a contributor, will looking forward to fix more stuff and maybe add something. I know same rule as always open PR for review, never push on master aka 1.0.x branch or similar.

**Comment by pitaj** [comment]
Thanks, @Fank. I'll consider adding you as a contributor with non-master branch access.

**Comment by Fank** [comment]
Could you please publish a new version with this fix?

**Comment by pitaj** [comment]
Of course

**Comment by pitaj** [comment]
I have to revert this because I can't reproduce the issue, and this change causes the user response to not be updated when the date is changed. We can continue discussion in #86

**Pull request merged**
