### PR TITLE
Create calendar.json

### PR DESCRIPTION
**Pull request by sohrabafard**
fa_IR language

### CODE REVIEW

**Comment by pitaj** [comment]
Your JSON is invalid. All keys must be surrounded in quotes.

**Comment by sohrabafard** [comment]
excuse me! I have very long days!

**Comment by pitaj** [comment]
Just one more thing: 

You are missing the `mandatory: "Mandatory"` field. It means required. Thanks!

**Comment by sohrabafard** [comment]
OK
    "mandatory": "اجباری"

**Pull request merged**
