### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by altembo**
here is a quick german translation for your plugin. 

Cheers

### CODE REVIEW

**Comment by pitaj** [comment]
Cool. Really quickly, what is "today" in German?

**Comment by altembo** [comment]
Its "Heute". I will update the translation as soon as your plugin works stable. At the moment the translations is being lost randomly and I am not able to add events on my Installation

**Comment by pitaj** [comment]
What do you mean by translations being lost?

**Comment by altembo** [comment]
Well there are to different Issues (I will add a Issue on Github soon)
1. some translation randomly dont work, like "event_name" and "place". So the german translation disappears and the default json tagnames appear.
2. all translations are disappearing in the admin panel and the default json tags appear. 

But I was not able to figure out the cause

**Pull request merged**
