### PR TITLE
v0.5.x and v0.6.x compatibility

### PR DESCRIPTION
**Pull request by julianlam**
For v0.5.0 compatible version of plugin:

* Added `async` to `package.json`, as it was probably installed globally in @pitaj's machine
* Added nbbpm compatibility string for proper recording of compatibility

### CODE REVIEW

**Comment by julianlam** [comment]
Okay, now I also fixed a couple of crashes on creating events, and updated the compatibility string for v0.6.x, but compatiblity isn't nearly complete.

**Comment by julianlam** [comment]
When merging:

* Publish 9fb388d first: `git checkout  9fb388d && npm version patch && npm publish`. Then the package will report compatibility correctly with v0.5.x in nbbpm

**Comment by julianlam** [comment]
This isn't nearly complete, as there are numerous bugs still present (missing labels, undefined values, etc), but it should get you started, hopefully!

**Comment by pitaj** [comment]
Yeah, I've done all of this already. I'm working on a major refactor. I've finished the back end, but I'm working on rewriting the front end right now. I should be done -pretty soon- sometime.

**Comment by pitaj** [comment]
Fixed in 0.2.x

**Pull request closed without merging**
